name: ak_azm_flutter
description: Ak AZM Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6
  sqflite: ^2.2.3
  path_provider: ^2.0.11
  path: ^1.8.2
  provider: ^6.0.5
  intl: ^0.17.0
  another_flushbar: ^1.12.29
  google_fonts: ^3.0.1
  flutter_localizations:
    sdk: flutter
  localization:
  dropdown_search: ^5.0.5
  indexed: ^0.0.8
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  collection: ^1.16.0
  jiffy: ^5.0.0
  flex_color_scheme: ^6.1.2
  printing: ^5.9.3
  flutter_html_to_pdf: ^0.7.0
  pdf: ^3.8.4
  tuple: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_native_splash: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_flavorizr: ^2.1.5
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  pigeon: ^7.1.4

flavorizr:
  flavors:
    development:
      app:
        name: "レポート作成(dev)"
      android:
        applicationId: "com.akzoll.rescuereportcreate"
      ios:
        bundleId: "com.akzoll.rescuereportcreate"

    production:
      app:
        name: "レポート作成"
      android:
        applicationId: "com.akzoll.rescuereportcreate"
      ios:
        bundleId: "com.akzoll.rescuereportcreate"

flutter:
  uses-material-design: true

  assets:
    - lib/i18n/
    - assets/template/
    - assets/img/
    - assets/example/
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
